# This workflow requires that the following repository variables have been created:
# - `ORGANIZATION_PROJECT__STATUS_VALUE_FOR_ADDED_ISSUES` - The value of the 'Status' field to set for issues when added to the project.
# in addition to the ones required by `_reusable_add-content-to-project.yml`.

name: Add issues to project

on:
  issues:
    types: [ opened, reopened ]

jobs:
  add_to_project:
    uses: ./.github/workflows/_reusable_add-content-to-project.yml
    with:
      content_id: ${{ github.event.issue.node_id }}
      status_field_value_name: ${{ vars.ORGANIZATION_PROJECT__STATUS_VALUE_FOR_ADDED_ISSUES }}
    secrets: inherit
